// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import NavBarController from "./NavBarController"; // Import the new component
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#222831] ${geistSans.variable} ${geistMono.variable}`}>
        <NavBarController /> {/* Use the NavBarController here */}
        {children}
      </body>
    </html>
  );
}
