player_ready1_id = content.get('player_ready1')
player_ready1_name = content.get('player_ready1_name')
player_ready1_img = content.get('player_ready1_img')
player_ready2_id = content.get('player_ready2')
player_ready2_name = content.get('player_ready2_name')
player_ready2_img = content.get('player_ready2_img')