import type { Metadata } from "next";
import localFont from "next/font/local";
import NavBarController from "./Components/NavBarController";
import "./globals.css";
import { WebSocketProvider } from "./game/webSocket" 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#222831] ${geistSans.variable} ${geistMono.variable}`}>
        <NavBarController />
        <WebSocketProvider>
          {children}
        </WebSocketProvider>
      </body>
    </html>
  );
}





// return (
//   <WebSocketProvider username={username}>
//     <Routes>
//       <Route path="/" element={<FirstComponent />} />
//       <Route path="/game" element={<GameComponent />} />
//     </Routes>
//   </WebSocketProvider>
// );
