
export const metadata = {
  title: "ping-pong",
  description: "Generated by : (abberkac)",
  viewport: 'width=device-width, initial-scale=1', // Correct placement of viewport meta tag
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`bg-[#222831]`}>
          {children}
      </body>
    </html>
  );
}