import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ping-pong",
  description: "Generated by : (abberkac)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#222831]`}>
          {children}
      </body>
    </html>
  );
}