
export const metadata = {
  title: "ping-pong",
  description: "Generated by : (abberkac)",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`bg-[#222831]`}>
          {children}
      </body>
    </html>
  );
}