import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "ping-pong",
  description: "Generated by : (abberkac)",
  
};
export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: 'no'
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`bg-[#222831]`}>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                background: "#ffffff",
                color: "#333333",
              },
            }}
          />
      </body>
    </html>
  );
}