# Generated by Django 5.1.1 on 2025-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='opponent_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
