# Generated by Django 5.1.1 on 2024-11-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameresult',
            old_name='goals_scored',
            new_name='opponentScore',
        ),
        migrations.RenameField(
            model_name='gameresult',
            old_name='opponent_goals',
            new_name='userScore',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='result',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='opponent',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
