# Generated by Django 5.1.1 on 2025-01-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameresult_opponent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='opponent_image',
        ),
    ]
