# Generated by Django 5.1.1 on 2024-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gameresult_opponent_alter_gameresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='opponent',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
