# Generated by Django 5.1.1 on 2025-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameresult_opponent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='user_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
