# Generated by Django 5.1.1 on 2025-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('intra42', 'Intra 42')], default='local', max_length=10),
        ),
    ]
