# Generated by Django 5.1.1 on 2025-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.FloatField(default=0),
        ),
    ]
