# Generated by Django 5.1.1 on 2024-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_achievement_matchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='matchhistory',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='myapp.achievement'),
        ),
        migrations.AddField(
            model_name='profile',
            name='matche_history',
            field=models.ManyToManyField(blank=True, related_name='match_history', to='myapp.matchhistory'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='result',
            field=models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss')], max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='matchhistory',
            unique_together={('user', 'match')},
        ),
    ]
