# Generated by Django 5.1.1 on 2024-11-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_achievement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='myapp.achievement'),
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
    ]
