# Generated by Django 5.1.1 on 2025-01-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
