# Generated by Django 5.1.1 on 2024-12-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
    ]
