# Generated by Django 5.1.1 on 2025-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('regular', 'Regular'), ('student', 'Student')], default='regular', max_length=10),
        ),
    ]
