# Generated by Django 5.1.1 on 2024-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='winrate',
            field=models.FloatField(default=0),
        ),
    ]
