# Generated by Django 5.1.1 on 2024-11-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_winrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leaderboard_rank',
            field=models.IntegerField(default=0),
        ),
    ]
